### ISSUE TITLE
On Intel CPU's, performance is much lower with ASM

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/trtl-stak#6]
In `cpu.txt`, swapping `"asm" : "auto",` to `"asm" : "off",` massively increases performance.

**Comment by brandonlehmann** [comment]
Bury the block at https://github.com/turtlecoin/trtl-stak/blob/0e728807ad5caeac9f7c6af01aba67dec637fa45/xmrstak/backend/cpu/minethd.cpp#L654 and auto will work again :)

**Comment by brandonlehmann** [comment]
More specifically https://github.com/turtlecoin/trtl-stak/blob/0e728807ad5caeac9f7c6af01aba67dec637fa45/xmrstak/backend/cpu/minethd.cpp#L657

**Comment by zpalmtree** [comment]
Maybe we'd get better performance if the ASM worked as expected? :smiley:

**Comment by brandonlehmann** [comment]
i'll give it a go with my AMD and see if it makes a difference as well.

**Comment by brandonlehmann** [comment]
Do YOU want to troubleshoot assembly code? Cuz I don't :)

**Comment by zpalmtree** [comment]
Hey, I don't see my name on the maintainer list :^)

**Comment by brandonlehmann** [comment]
> Maybe we'd get better performance if the ASM worked as expected? 😃

Do YOU want to troubleshoot assembly code? Cuz I don't :)

**Comment by brandonlehmann** [comment]
> Hey, I don't see my name on the maintainer list :^)

one second

**Comment by zpalmtree** [comment]
delet this

**Comment by Bathmat** [comment]
I was getting rejected shares with `"asm" : "auto"` on an i3-7350k. `"asm" : "off"` fixed the rejected shares. This was for a DeroGold pool.

**Comment by brandonlehmann** [comment]
Yup. Hoping to assemble a patch tonight or tomorrow.

**Comment by brandonlehmann** [comment]
@zpalmtree  does this float your boat?

https://github.com/turtlecoin/trtl-stak/commit/9667d43e92a28ea73e230dae08abd2d976ea20c8

**Comment by brandonlehmann** [comment]
Considering this handled in https://github.com/turtlecoin/trtl-stak/releases/tag/2.7.2-turtle
