### ISSUE TITLE
Libmicrohttpd10 missing

### ISSUE THREAD

**Issue by afterconnery** [turtlecoin/trtl-stak#7]
Getting this issue with 2.7.1 - 2.7.3
/xmr-stak: error while loading shared libraries: libmicrohttpd.so.10: cannot open shared object file: No such file or directory

Running Ubuntu Budgie 18.04 on core 2 duo machine. I have been recently using regular xmrstak but wanted to switch to new trtl algo to try it out.

2.7.1 works on my two other machines and they run 16.04 version of Ubuntu. I noticed they have libmicrohttpd10 and 18.04 has libmicrohttpd12. But this doesnt make sense as to why normal xmrstak works fine.

**Comment by brandonlehmann** [comment]
I suggest compiling locally on your machine or installing the v10 shared library.

**Comment by afterconnery** [comment]
I ended up cloning the repo and built it like regular xmrstak.

**Comment by brandonlehmann** [comment]
Awesome.
